# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('fed', models.BooleanField(choices=[(True, '\u0421\u044b\u0442'), (False, '\u0413\u043e\u043b\u043e\u0434\u0435\u043d')], default=False)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
